project:
  type: website
  output-dir: docs

website:
  title: "Ryo SHIOZAKI | 塩崎亮"
  navbar:
    left:
      - href: index.qmd
        text: Home
  page-footer: "..."

format:
  html:
    theme: cosmo
    toc: true



