project:
  type: website
  output-dir: docs

website:
  title: "Ryo SHIOZAKI | 塩崎亮"
  navbar:
    left:
      - href: index.qmd
        text: Home
  page-footer: "2024"
  google-analytics: "G-LVQYC7R777"

format:
  html:
    theme: cosmo
    toc: false



